// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	DueDate string `json:"dueDate"`
}

type NewItem struct {
	TodoListID int    `json:"todoListId"`
	Name       string `json:"name"`
	DueDate    string `json:"dueDate"`
}

type NewTodo struct {
	Name string `json:"name"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type TodoList struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Text  string  `json:"text"`
	Done  bool    `json:"done"`
	Items []*Item `json:"items"`
}
